[book]
authors = ["joshxyzhimself"]
language = "en"
multilingual = false
src = "src"
title = "Web Dev PH Resources"
description = "Resources for learning web development."

[output.html]
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/webdevph2/resources"
edit-url-template = "https://github.com/webdevph2/resources/edit/main/{path}"
cname = "resources.webdevph.info"