[book]
authors = ["joshxyzhimself"]
language = "en"
multilingual = false
src = "src"
title = "Learn Web Dev Resources"
description = "Resources for learning web development."

[output.html]
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/learnwebdevco/resources"
edit-url-template = "https://github.com/learnwebdevco/resources/edit/main/{path}"
cname = "resources.webdevph.info"